### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by reinzor** [tue-robotics/ed#10]
ed_server: /tmp/buildd/pcl-1.7-1.7.0/kdtree/include/pcl/kdtree/impl/kdtree_flann.hpp:172: int pcl::KdTreeFLANN<PointT, Dist>::radiusSearch(const PointT&, double, std::vector<int>&, std::vector<float>&, unsigned int) const [with PointT = pcl::PointNormal, Dist = flann::L2_Simple<float>]: Assertion `point_representation_->isValid (point) && "Invalid (NaN, Inf) point coordinates given to radiusSearch!"' failed.
[ed_server-29] process has died [pid 20144, exit code -6, cmd /home/amigo/ros/hydro/system/devel/lib/ed/ed_server /home/amigo/ros/hydro/system/src/ed/config/config_amigo.yml __name:=ed_server __log:=/home/amigo/.ros/log/179a12e8-5f45-11e4-82f0-00018080b210/ed_server-29.log].
log file: /home/amigo/.ros/log/179a12e8-5f45-11e4-82f0-00018080b210/ed_server-29*.log

**Comment by Rayman** [comment]
I haven't seen this error in a while so I assume it's fixed.
