### ISSUE TITLE
Implement a way for checking if something is 'in room X'

### ISSUE THREAD

**Issue by Rayman** [tue-robotics/ed#22]
This is for example needed in the base navigation to improve the constraint based planner:
- Go to table-1 in the kitchen

**Comment by rokusottervanger** [comment]
Added by tue-robotics/ed_navigation@f5b5f60bfc2c73f67abeaf819260c68efff85c72, and corresponding room models in tue-robotics/ed_object_models@b33f3fea376eb45f83d27075c10da98696992dac

**Comment by LoyVanBeek** [comment]
This is also very handy in the manipulation challenge.
How exactly can I query this?

**Comment by rokusottervanger** [comment]
You cannot actually query if something is in the room or in what room something is (yet). You can however tell navigateToSymbolic that something is in a certain room and the navigation constraint will be generated accordingly.
