### ISSUE TITLE
OpenCV crash

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/ed#25]
OpenCV Error: Bad flag (parameter or structure field) (Unrecognized or unsupported array type) in cvGetMat, file /tmp/buildd/ros-hydro-opencv2-2.4.9-2precise-20140819-1745/modules/core/src/array.cpp, line 2482
terminate called after throwing an instance of 'cv::Exception'
  what():  /tmp/buildd/ros-hydro-opencv2-2.4.9-2precise-20140819-1745/modules/core/src/array.cpp:2482: error: (-206) Unrecognized or unsupported array type in function cvGetMat

[ed_server-14] process has died [pid 17987, exit code -6, cmd /home/amigo/ros/hydro/system/devel/lib/ed/ed_server /home/amigo/ros/hydro/system/src/ed/config/amigo.yaml __name:=ed_server __log:=/home/amigo/.ros/log/7f8f5e36-964e-11e4-8f37-6cc217ec10f1/ed_server-14.log].
log file: /home/amigo/.ros/log/7f8f5e36-964e-11e4-8f37-6cc217ec10f1/ed_server-14*.log

**Comment by rokusottervanger** [comment]
Is this still an issue?

**Comment by LFBFerreira** [comment]
If it was the same i used to have, Sjoerd fixed it a couple of weeks ago. I will close this since no has complained about OpenCV Crashes on ED for several weeks
