### ISSUE TITLE
Query items in a given volume

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/ed#27]
In ED, you can get all Entities that are withing a sphere (e.g. within some radius to a given point).
It is very handy if we can get all entities with e.g.  a box/cylinder/sphere/(mesh?) relative to some frame.
You an use this for querying all items in a room but also all items on a table, a shelf etc.

Maybe the [Shape_msgs](http://wiki.ros.org/shape_msgs) can help.

**Comment by Rayman** [comment]
This is related to #22

**Comment by rokusottervanger** [comment]
You can do something like this using a custom criteria function in an edEntityDesignator. In the wakemeup challenge I used this to check if there was an entity within the convex hull of the bed. For a room (which doesn't have a chull) you could check in the same way if it is inside the "in" box defined in the "areas" data. Is that sufficient?

**Comment by LoyVanBeek** [comment]
Yes, i think @jlunenburg already has a few functions in the library for this sort of thing.
