### ISSUE TITLE
Igonore detected entities above a certain heigth

### ISSUE THREAD

**Issue by LFBFerreira** [tue-robotics/ed#28]
If Amigo is looking up he will segment lamps, metal beams or the window divisions on our lab for example. Either create a ceiling or add a parameter in the config file to ignore detections above a certain height

**Comment by Rayman** [comment]
This was fixed by tue-robotics/ed_navigation@fdd7e99a1f5c50f215c4a79ca0cbca4cdd44c7cd I think.
