### ISSUE TITLE
"Error getting map data" constant output

### ISSUE THREAD

**Issue by LFBFerreira** [tue-robotics/ed#30]
When an empty map is used in ED config, there is a constant output that says:

Error getting map data:
width: -799999999
length: -799999999

**Comment by LoyVanBeek** [comment]
What causes this error exactly? 
I'm getting 

    Error getting map data:
    width: -39999960
    height: -39999960
    resolution: 0.05
    Error getting map data:
    width: -79999920
    height: -79999920
    resolution: 0.025

on Rose while the map is being published on /map.

**Comment by jlunenburg** [comment]
I believe this has to do with the 'loc_grid_publisher', which can be removed from the config. This is not used anyway (for localization there is another plugin).

**Comment by rokusottervanger** [comment]
I'm guessing you are simulating with an empty world? The loc_grid_publisher builds a grid from the ed entities in the world. If the world is empty, it is unable to do that.

**Comment by jlunenburg** [comment]
Or if there are no 'localizable' entities I guess

**Comment by LoyVanBeek** [comment]
Disabling both loc_grid_publisher and obstacle_grid_publisher got rid of the error.

**Comment by jlunenburg** [comment]
The obstacle_grid_map_publisher is required for navigation though, so if you want to use that we need to fix the plugin. Again, I guess it has already been fixed in the other branch I mentioned

**Comment by LoyVanBeek** [comment]
I thought so already. It worked before on an older version (around christmas) but I'll try the branch first.
