### ISSUE TITLE
[occupancy_grid_publisher_plugin] Error getting map data:

### ISSUE THREAD

**Issue by Rayman** [tue-robotics/ed#33]
On ROS indigo I keep getting this error:
```
Error getting map data:
width: -39999960
height: -39999960
resolution: 0.05
Error getting map data:
width: -39999960
height: -39999960
resolution: 0.05
```
@reinzor you wrote this error, what could be the cause?

**Comment by reinzor** [comment]
This is due to the localization map that is being published with a
specifier localizable. No models are selected so there is nothing to be
published.



-Rein
