### ISSUE TITLE
Ed crashes with OpenCV error

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/ed#36]
OpenCV Error: Assertion failed (rect.width >= 0 && rect.height >= 0 && rect.x < image->width && rect.y < image->height && rect.x + rect.width >= (int)(rect.width > 0) && rect.y + rect.height >= (int)(rect.height > 0)) in cvSetImageROI, file /tmp/buildd/ros-hydro-opencv2-2.4.9-2precise-20141231-1923/modules/core/src/array.cpp, line 3006
terminate called after throwing an instance of 'cv::Exception'
  what():  /tmp/buildd/ros-hydro-opencv2-2.4.9-2precise-20141231-1923/modules/core/src/array.cpp:3006: error: (-215) rect.width >= 0 && rect.height >= 0 && rect.x < image->width && rect.y < image->height && rect.x + rect.width >= (int)(rect.width > 0) && rect.y + rect.height >= (int)(rect.height > 0) in function cvSetImageROI

[amigo/ed-13] process has died [pid 27858, exit code -6, cmd /home/amigo/ros/hydro/system/devel/lib/ed/ed /home/amigo/ros/hydro/system/src/amigo_bringup/parameters/world_modeling/world_model.yaml __name:=ed __log:=/home/amigo/.ros/log/162ccd16-bdf9-11e4-af5c-0090f5cdbcde/amigo-ed-13.log].
log file: /home/amigo/.ros/log/162ccd16-bdf9-11e4-af5c-0090f5cdbcde/amigo-ed-13*.log

**Comment by rokusottervanger** [comment]
Is this still an issue?
