### ISSUE TITLE
Rounding error?

### ISSUE THREAD

**Issue by LoyVanBeek** [tue-robotics/ed#41]
amigo@amigo3 $ rosservice call /amigo/ed/simple_query "id: ''
type: ''
center_point:
  x: 0.0
  y: 0.0
  z: 0.0
radius: 0.0" 
ERROR: service [/amigo/ed/simple_query] responded with an error: Error in function boost::math::round<d>(d): Value -nan can not be represented in the target integer type.

**Comment by svddries** [comment]
Fixed in 8b8dda6
