### ISSUE TITLE
Error during catkin_make 'getModelFilePath’ is not a member of ‘sdf'

### ISSUE THREAD

**Issue by Pranav24-8** [tue-robotics/ed#93]
I get the following error during catkin_make. I have cloned all the required repositories. Please help.

```bash
[ 84%] Building CXX object prj-iki-robotics/knowledgebase/ed/CMakeFiles/ed_core.dir/src/models/model_loader.cpp.o
/home/iki/catkin_ws/src/prj-iki-robotics/knowledgebase/ed/src/models/model_loader.cpp: In member function ‘std::__cxx11::string ed::models::ModelLoader::getSDFPath(const string&) const’:
/home/iki/catkin_ws/src/prj-iki-robotics/knowledgebase/ed/src/models/model_loader.cpp:118:56: error: ‘getModelFilePath’ is not a member of ‘sdf’
                     tue::filesystem::Path model_path = sdf::getModelFilePath(mo
                                                        ^
prj-iki-robotics/knowledgebase/ed/CMakeFiles/ed_core.dir/build.make:230: recipe for target 'prj-iki-robotics/knowledgebase/ed/CMakeFiles/ed_core.dir/src/models/model_loader.cpp.o' failed
make[2]: *** [prj-iki-robotics/knowledgebase/ed/CMakeFiles/ed_core.dir/src/models/model_loader.cpp.o] Error 1
CMakeFiles/Makefile2:11725: recipe for target 'prj-iki-robotics/knowledgebase/ed/CMakeFiles/ed_core.dir/all' failed
make[1]: *** [prj-iki-robotics/knowledgebase/ed/CMakeFiles/ed_core.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j16 -l16" failed
```

**Comment by MatthijsBurgh** [comment]
Hey,

Did you install the SDF library according to the [README.md](https://github.com/tue-robotics/ed/blob/master/README.md)?

**Comment by Pranav24-8** [comment]
Ya I installed libsdformat4-dev.

**Comment by MatthijsBurgh** [comment]
Could please provide more information about your system?

Please include the version info of `libsdformat4-dev` (use apt-cache policy)

**Comment by Pranav24-8** [comment]
Hi, sorry for the delay.
I am using: 
Ubuntu 16.04
ROS-Kinetic
libsdformat4-dev:
  Installed: 4.0.0-1ubuntu2
  Candidate: 4.0.0-1ubuntu2
  Version table:
 *** 4.0.0-1ubuntu2 500
        500 http://de.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
        100 /var/lib/dpkg/status

**Comment by MatthijsBurgh** [comment]
The SDF library is too old. As mentioned in the README, you need minimal 4.4. Please follow the instructions in the README to get a newer version.

**Comment by Pranav24-8** [comment]
Alright got it. Thank you.

**Comment by Pranav24-8** [comment]
libsdformat4-dev:
  Installed: 4.0.0-1ubuntu2
  Candidate: 4.4.0-1~xenial
  Version table:
     4.4.0-1~xenial 500
        500 http://packages.osrfoundation.org/gazebo/ubuntu-stable xenial/main amd64 Packages
 *** 4.0.0-1ubuntu2 500
        500 http://de.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
        100 /var/lib/dpkg/status
Followed the steps in ReadMe. But still getting the error. Looks like I need to switch to the newer version. But I do not know how.

**Comment by MatthijsBurgh** [comment]
`sudo apt-get upgrade libsdformat4-dev`?

**Comment by Pranav24-8** [comment]
```bash
[ 83%] Building CXX object prj-iki-robotics/knowledgebase/ed/CMakeFiles/ed_core.dir/src/models/model_loader.cpp.o
/home/iki/catkin_ws/src/prj-iki-robotics/knowledgebase/ed/src/models/model_loader.cpp:17:25: fatal error: sdf/parser.hh: No such file or directory
compilation terminated.
prj-iki-robotics/knowledgebase/ed/CMakeFiles/ed_core.dir/build.make:230: recipe for target 'prj-iki-robotics/knowledgebase/ed/CMakeFiles/ed_core.dir/src/models/model_loader.cpp.o' failed
make[2]: *** [prj-iki-robotics/knowledgebase/ed/CMakeFiles/ed_core.dir/src/models/model_loader.cpp.o] Error 1
CMakeFiles/Makefile2:11689: recipe for target 'prj-iki-robotics/knowledgebase/ed/CMakeFiles/ed_core.dir/all' failed
make[1]: *** [prj-iki-robotics/knowledgebase/ed/CMakeFiles/ed_core.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j16 -l16" failed
```
Same place. Different error now.

**Comment by MatthijsBurgh** [comment]
Can you confirm that you know do have 4.4.0? Please clean your workspace and build your workspace again.

**Comment by MatthijsBurgh** [comment]
I assume your problem has been solved.
